export const env={
    baseUrl:"http://localhost:8089/api",
    loginUrl:"/login",
    saveUser:"/company/save",
    refreshToken:"/token/refresh",
    demandToResetPassword : "/reset-password/",
    resetPassword : "/confirm-password/",
    confirmationToken : "/ConfirmationToken/",
    getUsers : "/company/users",
    registerUser : "/company/save",
    getDataTable : "/get/",
    getLists:"/lists/",
    getTables:"/tables/",
    getCards:"/cards/",
    updateList : "/List/update/",
    updateCard : "/Card/update/",
    saveList:"/list/save/",
    saveCard:"/card/",
    savveCard:"/save",
    getProjects:"/projects/",
    getUser:"/user/",
    deleteList:"/list/delete/",
    updateTable:"/Table/update/",
    getToDo :"/ToDo/",
    saveSprint:"/sprint/save/",
    getsprints:"/sprints/",
    deleteSprint:"/sprint/delete/",
    saveCardSprint:"/cardSprint/save/",
    getcardsSprint : "/cardsSprint/",
    updateSprint : "/Sprint/update/",
   charts:"/charts"

}